#日志
logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

#服务名、端口配置
server:
  port: 8080
  servlet:
    context-path : /sbj

#数据库连接配置
spring:
  profiles:
    active: sit
  datasource:
    username: ${sct.db.username}
    password: ${sct.db.password}
    url: jdbc:mysql://${sct.db.address}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&usessl=true&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid: #如果使用 druid-springboot-starter 可在配置文件直接配置druid相关属性
      initial-size: 1 #初始化连接大小
      max-active: 10 #最大连接数
      min-idle: 1   #最小空闲连接数
      max-wait: 60000 #配置获取连接等待超时的时间(毫秒)
      pool-prepared-statements: false #是否缓存PreparedStatement. PSCache对支持游标的数据库性能提升巨大，比如说oracle.在mysql下建议关闭.
      max-pool-prepared-statement-per-connection-size: 20 #每个连接上PSCache的大小
      validation-query: SELECT 'x' #用来检测连接是否有效的sql
      validation-query-timeout: 10 #指定连接校验查询的超时时间
      test-on-borrow: true #当从连接池借用连接时，是否测试该连接
      test-on-return: false #在连接归还到连接池时是否测试该连接
      test-while-idle: false #当连接空闲时，是否执行连接测试
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      # create：每次运行程序时，都会重新创建表，故而数据会丢失
      # create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
      # upadte：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
      # validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
      # none: 禁用DDL处理
      ddl-auto: validate