node{
    stage('Check Out'){
        //check CODE
      git credentialsId: 'git-key',
      url: 'https://github.com/Vigin-Tse/Spring-boot-redis.git'
    }

    //定义mvn环境
    def mvnHome = tool 'maven'
    env.PATH = "${mvnHome}/bin:${env.PATH}"

    stage('ProjectBuild'){
        //mvn构建
        sh "mvn clean install -Dmaven.test.skip=true"
    }

    stage('ImageBuild'){
    def imagesName = '172.18.118.25:9003/spring-boot-redis:lastest'
        docker.build(imagesName).push()
    }
}