version: '2'
services:
  jenkins:
    restart: always #在容器停止运行的时候，重启容器。用于开机自启和容器意外关闭时的自启动
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '9001:8080'
      - '9002:50000'
    volumes:
      - /var/jenkins_home:/var/jenkins_home #将宿主机的 /var/jenkins_home 目录挂载到 /var/jenkins_home
      - /home/apache-maven-3.6.3:/usr/local/maven #将宿主机的 /home/apache-maven-3.6.3 目录挂载到挂在Maven目录
      - /home/jdk1.8.0_241:/usr/local/jdk #宿主机jdk挂载
#      - /usr/local/git:/usr/local/git #git 挂载
      - /var/run/docker.sock:/var/run/docker.sock
    mem_limit: 1020m